### ISSUE TITLE
Duplicated time in older games

### ISSUE THREAD

**Issue by guga31bb** [CroppedClamp/nfl_pbps#1]
See [here](https://github.com/mrcaseb/nflfastR/issues/35#issuecomment-656954185)- is this a problem in the underlying data? There's a few older games like this.

**Comment by CroppedClamp** [comment]
Yeah, this is an artifact of when games didn't actually include per-snap times. So times are just carried over from the most recent time of possession beginning

**Comment by guga31bb** [comment]
Thanks! That's what I assumed but thought I would check
